name: Context Example

on:
  push:

jobs:
  context-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Job Context
        run: echo "Job Context is ${{ toJson(job) }}"
      - name: Show Job steps
        run: echo "Job Context is ${{ toJson(steps) }}"



            