name: Matrix Exclude Example

on: push

jobs:
  test_matrix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16, 18]

        exclude:
          - os: windows-latest
            node: 18   # ‚ùå this combination will NOT run

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: echo "Running on OS=${{ matrix.os }} Node=${{ matrix.node }}"
