name: Matrix Include Example

on: push

jobs:
  test_matrix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]   # default matrix
        node: [16, 18]                        # default Node versions

        # âž• Include extra custom combinations
        include:
          - os: ubuntu-latest
            node: 20
          - os: windows-latest
            node: 14

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: echo "Running on OS=${{ matrix.os }} Node=${{ matrix.node }}"
