name: Run Multiple job

on: push

jobs:
    
    build_job:
        
        runs-on: ubuntu-latest
        

        steps:
        - uses: actions/checkout@v6
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute the cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon.....Uicjidn" >> dragon.txt

    test_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - name: sleep for 10 seconds
          run: sleep 10

        - name: Test file exist
          run: grep -i "dragon" dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v6
        - name: Read the file
          run: cat dragon.txt

          

        
